### ISSUE TITLE
The pre-computed features are empty

### ISSUE THREAD

**Issue by liujiaheng** [BCV-Uniandes/PNG#3]
![image](https://user-images.githubusercontent.com/27964642/133718544-7025f326-a384-4472-a7f7-7747e33b1b2b.png)

Hi, this is a nice work. The pre-computed features are empty on your website.
Looking forward to your reply.

Jiaheng.

**Comment by cigonzalez** [comment]
Hi Jiaheng,

Thank you for your interest in our work. Also thanking for pointing it out. Now you should be able to download the pre-computed features for the validation split. In case you get redirected to the same error page, try clearing your browser cache. Just let me know if you still have any issues.

Best,
Cristina González
